### ISSUE TITLE
Setup SPV for Dev activities

### ISSUE THREAD

**Issue by atticbee** [rchain-community/sm19a#1]
Rough idea:
Spin off Dev team to a separate entity, which could be isolated from Coop mismanagement & bankruptcy.
Coop is mainly responsible for operating the platform, and the new entity focus on dev.
Coop allocates enough RHOCs to the SPV, and transfers the Dev cut part of mainnet mining revenue to SPV.
If Coop bankrupts, community can still contribute to the SPV in exchange of RHOCs & mining cut & other services, to ensure the development still goes on.

**Comment by nmeyne** [comment]
Sounds good to me.  It's also what I was thinking of as a 'Platform Services Agency' shown in slide 20 in here:  https://docs.google.com/presentation/d/1A8VtRfjxBZ_8InCxgfog3SzufbZo45t-OujZcJWQC-A/edit?usp=sharing

I didn't specify how it could be resourced ...  yes the RHOC funding and a cut of mainnet mining could be a good way to do this.  The idea of 'exchange of other services' part is also interesting...   a sort of IOU for future development days on members own projects.   A sort of local currency that helps build a sense of community and trust?   Not there yet though.

**Comment by richjensen3000** [comment]
Harmonizes with a notion I've had for a 'time-based co-op currency' perhaps secured fractionally against a fund from member dues, co-op branded merch, and perhaps someday, tx fees from an internal Members good and services trading platform. Account for engaged co-op time.

**Comment by dckc** [comment]
rdev was introduced by @leithaus in [debrief 192 Aug 19, 2020](https://blog.rchain.coop/2020/08/23/rchain-co-op-weekly-community-debrief-192-aug-19-2020/) at 12:26.

See also [Log-RDev-coop](https://docs.google.com/document/d/1NImbkoxPoL5hI4GtTl6ziOC8TcvdeSUOEwlz4hViV34/edit), [#rdev-coop](https://discord.com/channels/375365542359465989/) channel.

Given these developments, I'm no longer interested in tracking this issue here.
