### ISSUE TITLE
'Barcelona' Transaction Report

### ISSUE THREAD

**Issue by nmeyne** [rchain-community/sm19a#14]
The members propose that the President should commission, contribute to and publish a complete account of the Barcelona transaction, with a independent assessment, including any likely legislative/jurisdictional risk.  See the template proposed by Mark Pui:  https://cdn.discordapp.com/attachments/512346605727514634/573650122911645707/RChain_-_Summary_of_Fraud_Incident.pdf

**Comment by dckc** [comment]
Can you think of anyone in a position to make a useful next step on this, @nmeyne? I'm giving you the ball, for now.

Let's try to turn the corner from brainstorming to actually tracking issues to resolution.

**Comment by richjensen3000** [comment]
Should this be an AFC or ExCom task?

**Comment by dckc** [comment]
Yes. :)

That is: either one would work for me.

The AFC met more recently and might have more momentum.

**Comment by nmeyne** [comment]
I think if Mark Pui and Ian Bloom had the appetite to complete this it would be a great help.


Nick

**Comment by richjensen3000** [comment]
So, perhaps issue should be amended from President to AFC.

**Comment by dckc** [comment]
Frankly, I find the [whole story](https://blog.rchain.coop/blog/2019/04/26/rchain-update-04-26-19/) rather hard to believe. That blog item is signed "RChain Staff", despite my repeated requests that they be signed by individuals. @derekberes I infer you actually posted it, if not wrote it? The story names @leithaus , so most likely you got the story from him. @swanzer @KentShikama @ned-robinson, feel free to point this comment out to the other RChain staff: Lilia R., Ian B., Tim M.

What is the name and contact info / reputation (such as a DUNS number) of the trusted third party? Isn't the very nature of an escrow service such that "once the money was in escrow", if the funds turn out to be bad, the loss is theirs rather than ours?

The coop RHOC are held in multi-sig contracts, right? Who were the multiple parties who signed the transaction?

Who has access to the FBI report? Could we please get a letter from coop council acknowledging receipt of the FBI report? Would someone please take an accountable role in communicating periodic updates on the case? Perhaps monthly or quarterly?

**Comment by nmeyne** [comment]
It might be useful if the report also investigated the regulatory position on the Barcelona deal. Paragraph 6 here is relevant perhaps:
https://www.globallegalinsights.com/practice-areas/blockchain-laws-and-regulations/spain#chaptercontent6

**Comment by dckc** [comment]
At 33:24 into the [July 17 debrief][17Jul], Greg updated the community on KuCoin, which has started allowing withdrawals. He explained that one of the hold-ups was miscommunication about a request from KuCoin to get police reports. Forwarded communications with the FBI didn't satisfy KuCoin, but a report to the Spanish authorities did.

That seems like credible independent verification of a police report.

While I would rather be informed of what reputation was known about the escrow service when it was chosen, I suppose that addresses this issue to my satisfaction. @nmeyne and everybody else, feel free to reopen it.

[17Jul]: https://youtu.be/3Ncy69MIiGI

**Comment by richjensen3000** [comment]
Can anyone give a reason why this documentation has never been shared with members?

**Comment by dckc** [comment]
The police report presumably contains sensitive material. Producing a redacted report was evidently not given priority over other tasks.

There's also a risk that one or more members would not respect confidentiality. That risk might be a reason not to share the info. (Not that I think it's a conclusive argument; just that it's _a_ reason.)

**Comment by dckc** [comment]
> While I would rather be informed of what reputation was known about the escrow service when it was chosen, I suppose that addresses this issue to my satisfaction.

I'm no longer satisfied without this information being shared at least to the membership.

See also: [RChain Blues](https://www.madmode.com/2019/rchain-blues.html) 2019-06-05

ref [request Feb 28, 2020](https://discordapp.com/channels/375365542359465989/595813040759242794/683009825486930059)

**Comment by dckc** [comment]
Some relevant information was shared with the membership.

In particular, the tokens were recovered in the genesis block.
